"""
Deterministic dossier → draft module + draft expectation.

Imitates the `atlas ingest` pattern (`parker_atlas.ingest.prevalence`): build a
plain dict, render it to YAML, then round-trip the rendered string through the
*real* runtime loader. If the generated artifact would not load, synthesis
fails here — at author time — rather than later at `atlas generate` /
`atlas validate --cohort` time.

No LLM runs in this module: given a dossier, the output is a pure function of
it, so the draft module and expectation are mechanically auditable and
unit-testable.
"""

from __future__ import annotations

from typing import Any

import yaml

from parker_atlas.author.dossier import SNOMED_SYSTEM, Dossier
from parker_atlas.modules.runtime import ModuleError, load_module_from_str
from parker_atlas.validation.expectations import (
    ExpectationError,
    load_expectation_from_str,
)

DRAFT_BANNER = (
    "# DRAFT — unreviewed; generated by `atlas author` from a research dossier.\n"
    "# Do NOT ship until a licensed clinician has signed off (see SIGNOFF.md).\n"
)


class AuthorError(ValueError):
    """Raised when a dossier cannot be synthesized into a valid artifact."""


def synthesize_module(dossier: Dossier, *, banner: bool = True) -> str:
    """Render a draft module YAML from a dossier and validate it.

    Round-trips through `load_module_from_str`; a `ModuleError` is re-raised as
    `AuthorError` so callers handle a single exception type.
    """
    condition = dossier.condition
    emits: list[dict[str, Any]] = []

    # Encounters first so observation/medication link_to targets resolve.
    for enc in dossier.encounters:
        spec: dict[str, Any] = {
            "resource_type": "Encounter",
            "spec_id": enc["spec_id"],
            "when": "onset",
            "encounter_class": enc["class"],
            "type": enc["type"],
        }
        if enc.get("reason"):
            spec["reason"] = enc["reason"]
        emits.append(spec)

    for obs in dossier.observations:
        spec = {
            "resource_type": "Observation",
            "spec_id": obs["spec_id"],
            "when": "onset",
            "category": obs["category"],
            "code": obs["loinc"],
            "value_range": obs["value_range"],
            "unit": obs["unit"],
        }
        if obs.get("unit_code"):
            spec["unit_code"] = obs["unit_code"]
        if obs.get("link_to"):
            spec["link_to"] = obs["link_to"]
        emits.append(spec)

    for med in dossier.medications:
        spec = {
            "resource_type": "MedicationRequest",
            "spec_id": med["spec_id"],
            "when": "onset",
            "medication": med["medication"],
            "probability": med["fraction"],
        }
        if med.get("link_to"):
            spec["link_to"] = med["link_to"]
        emits.append(spec)

    condition_block: dict[str, Any] = {
        "id": condition,
        "code": dossier.snomed,
        "prevalence": dossier.prevalence_cells,
        "onset_age": {"min": dossier.onset_min, "max": dossier.onset_max},
    }
    if dossier.progressions:
        condition_block["progressions"] = [
            {"to": p["to"], "after_years": p["after_years"], "probability": p["probability"]}
            for p in dossier.progressions
        ]
    if emits:
        condition_block["emits"] = emits

    module = {
        "module": condition,
        "version": dossier.version,
        "description": _module_description(dossier),
        "cites": dossier.all_citations,
        "conditions": [condition_block],
    }

    rendered = _dump_yaml(module)
    if banner:
        rendered = DRAFT_BANNER + rendered

    try:
        load_module_from_str(rendered)
    except ModuleError as exc:
        raise AuthorError(f"synthesized module failed runtime validation: {exc}") from exc
    return rendered


def synthesize_expectation(dossier: Dossier) -> str:
    """Render a draft fidelity expectation YAML from a dossier and validate it.

    Provenance is `sourced`: the prevalence cells are cited but have not been
    independently re-verified against microdata by the project — exactly the
    guarantee a research pass provides. Tolerance mirrors the bundled
    convention (Wilson score CI at 99% confidence).
    """
    cit = dossier.prevalence_citation
    metric_id = (
        f"{dossier.condition}_prevalence_by_sex_and_age"
        if dossier.prevalence_stratify_by == "sex_and_age"
        else f"{dossier.condition}_prevalence_by_age"
    )

    expectation = {
        "module": dossier.condition,
        "version": dossier.version,
        "source": {
            "name": cit.get("source", ""),
            "provenance": "sourced",
            "url": cit.get("url", ""),
            "note": cit.get("summary", cit.get("note", "")),
            "citations": [
                {
                    "source": cit.get("source", ""),
                    "url": cit.get("url", ""),
                    "table": cit.get("table", ""),
                    "accessed": cit.get("accessed", ""),
                    "note": cit.get("summary", cit.get("note", "")),
                }
            ],
        },
        "metrics": [
            {
                "id": metric_id,
                "kind": "conditional_prevalence",
                "condition_code": dossier.snomed["code"],
                "condition_system": dossier.snomed.get("system", SNOMED_SYSTEM),
                "stratify_by": dossier.prevalence_stratify_by,
                "tolerance": {"kind": "wilson", "confidence": 99},
                "targets": dossier.prevalence_cells,
            }
        ],
    }

    rendered = _dump_yaml(expectation)
    try:
        load_expectation_from_str(rendered)
    except ExpectationError as exc:
        raise AuthorError(
            f"synthesized expectation failed runtime validation: {exc}"
        ) from exc
    return rendered


def _module_description(dossier: Dossier) -> str:
    """Build the module description.

    This text is permanent module metadata: it survives promotion, so it must
    read correctly both as a draft and once shipped. The *draft* signal lives in
    the `DRAFT_BANNER` comment (stripped on promote) and the SIGNOFF.md gate —
    NOT here. So the description states provenance, not lifecycle status.
    """
    method = dossier.generated.get("method", "manual")
    src = dossier.prevalence_citation.get("source", "an unnamed source")
    parts = [
        f"Auto-drafted by `atlas author` from a research dossier (method={method}). "
        f"Prevalence sourced from {src}.",
    ]
    if dossier.notes:
        parts.append(dossier.notes)
    return " ".join(parts)


class _NoAliasDumper(yaml.SafeDumper):
    """SafeDumper that never emits anchors/aliases (matches the ingest dumper)."""

    def ignore_aliases(self, _data: Any) -> bool:
        return True


def _dump_yaml(obj: Any) -> str:
    return yaml.dump(
        obj,
        Dumper=_NoAliasDumper,
        sort_keys=False,
        default_flow_style=False,
        allow_unicode=True,
        width=100,
    )
