"""Template-based discharge summary notes."""

from __future__ import annotations

from parker_atlas.notes.progress import (
    NoteContext,
    _collect_active_medications,
    _collect_recent_observations,
    _format_diagnosis_line,
    _format_observation_line,
)


def build_discharge_summary_text(
    ctx: NoteContext,
    *,
    encounter_class: str,
    admission_date: str | None = None,
) -> str:
    """Render a markdown discharge summary grounded in structured context."""
    if not ctx.diagnoses:
        problem_list = "_No active problems on file._"
    else:
        problem_list = "\n".join(_format_diagnosis_line(dx) for dx in ctx.diagnoses)

    primary = ctx.primary_diagnosis or (ctx.diagnoses[0] if ctx.diagnoses else None)
    primary_display = (
        primary.condition.code.display if primary is not None else "hospitalization"
    )

    observations = _collect_recent_observations(ctx.diagnoses)
    medications = _collect_active_medications(ctx.diagnoses)

    objective_lines = (
        [_format_observation_line(o) for o in observations]
        if observations
        else ["_No vitals or labs on file for this admission._"]
    )
    medication_lines = (
        [f"- {m}" for m in medications]
        if medications
        else ["_None on file._"]
    )

    setting = "inpatient" if encounter_class == "IMP" else "emergency department"
    admit_line = (
        f"**Admission date:** {admission_date}"
        if admission_date
        else "**Admission date:** not documented in synthetic record"
    )

    lines: list[str] = [
        "# Discharge Summary",
        "",
        f"**Patient:** {ctx.patient_display_name}",
        f"**Age / Sex:** {ctx.age_years} / {ctx.sex}",
        f"**Discharge date:** {ctx.today.isoformat()}",
        admit_line,
        f"**Setting:** {setting.title()} ({encounter_class})",
        "",
        "## Principal diagnosis",
        f"- {primary_display}",
        "",
        "## Problem list at discharge",
        problem_list,
        "",
        "## Hospital course",
        f"Patient presented to the {setting} for management of {primary_display}. "
        "Synthetic hospital course: evaluation, treatment, and stabilization per "
        "module-emitted encounters, procedures, and medications. "
        "No complications documented in this synthetic record.",
        "",
        "## Discharge condition",
        "Stable for discharge to home with outpatient follow-up arranged.",
        "",
        "## Discharge vitals & labs (most recent)",
        *objective_lines,
        "",
        "## Discharge medications",
        *medication_lines,
        "",
        "## Follow-up",
        f"- Outpatient follow-up for {primary_display} within 1-2 weeks.",
        "- Return precautions reviewed (worsening symptoms, medication intolerance).",
        "",
        "---",
        "_Generated by APEX Atlas (template mode). "
        "This is synthetic data; no real patient is depicted._",
    ]
    return "\n".join(lines)
