"""
Template-based progress notes.

The note generator takes structured patient + diagnosis data and emits a
plaintext markdown note. It is deterministic given its inputs (no RNG,
no calls out), which keeps generated notes reproducible across seeded
runs.

LLM-mode is a stub: the strategy enum and dispatch surface exist so
future authoring can swap in an LLM call without changing the call
sites that drive `atlas generate --with-notes`.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date
from enum import Enum

from parker_atlas.modules.runtime import Diagnosis


class NoteStrategy(str, Enum):
    TEMPLATE = "template"
    LLM = "llm"  # Reserved for M4; raises NotImplementedError today.


@dataclass(frozen=True)
class NoteContext:
    """Structured inputs the templates draw from.

    The template-mode renderer uses only these fields. The eventual LLM
    mode will receive the same context plus the full `diagnosis` so it
    can ground generation against the same structured data.
    """

    patient_display_name: str
    age_years: int
    sex: str  # "female" | "male" — matches AdministrativeGender values
    today: date
    diagnoses: tuple[Diagnosis, ...] = field(default_factory=tuple)


def _format_diagnosis_line(dx: Diagnosis) -> str:
    code = dx.condition.code
    onset = (
        f" (onset {dx.onset_date.isoformat()})"
        if dx.onset_date is not None
        else ""
    )
    return f"- {code.display} ({code.system} {code.code}){onset}"


def build_progress_note_text(ctx: NoteContext) -> str:
    """Render a markdown progress note from structured context.

    The body is intentionally short and skeletal — this is scaffolding
    that gives the pipeline a real DocumentReference to attach, not a
    pretense of a clinically-realistic narrative. M4's LLM-assisted
    authoring will replace this body while keeping the surrounding
    plumbing identical.
    """
    if not ctx.diagnoses:
        problem_list = "_No active problems on file._"
    else:
        problem_list = "\n".join(_format_diagnosis_line(dx) for dx in ctx.diagnoses)

    primary = ctx.diagnoses[0] if ctx.diagnoses else None
    primary_display = (
        primary.condition.code.display if primary is not None else "general care"
    )

    lines = [
        f"# Progress Note",
        f"",
        f"**Patient:** {ctx.patient_display_name}",
        f"**Age / Sex:** {ctx.age_years} / {ctx.sex}",
        f"**Date:** {ctx.today.isoformat()}",
        f"",
        f"## Active Problems",
        problem_list,
        f"",
        f"## Subjective",
        f"Patient seen today for follow-up of {primary_display}.",
        f"No new acute complaints documented in this synthetic record.",
        f"",
        f"## Assessment & Plan",
        f"Continue current management. Reassess at next routine follow-up.",
        f"",
        f"---",
        f"_Generated by Parker Atlas (template mode). "
        f"This is synthetic data; no real patient is depicted._",
    ]
    return "\n".join(lines)


def render_note(ctx: NoteContext, strategy: NoteStrategy = NoteStrategy.TEMPLATE) -> str:
    """Dispatch to the chosen renderer. LLM mode is reserved for M4."""
    if strategy is NoteStrategy.TEMPLATE:
        return build_progress_note_text(ctx)
    if strategy is NoteStrategy.LLM:
        raise NotImplementedError(
            "NoteStrategy.LLM is reserved for Milestone 4. "
            "Use NoteStrategy.TEMPLATE for the current build."
        )
    raise ValueError(f"unknown NoteStrategy: {strategy!r}")
