"""Template-based radiology report notes linked to imaging procedures."""

from __future__ import annotations

from parker_atlas.modules.runtime import SampledProcedure
from parker_atlas.notes.progress import NoteContext


def build_radiology_report_text(
    ctx: NoteContext,
    procedure: SampledProcedure,
) -> str:
    """Render a markdown radiology report for one imaging procedure."""
    primary = ctx.primary_diagnosis or (ctx.diagnoses[0] if ctx.diagnoses else None)
    indication = (
        primary.condition.code.display if primary is not None else "clinical indication"
    )

    lines: list[str] = [
        "# Radiology Report",
        "",
        f"**Patient:** {ctx.patient_display_name}",
        f"**Age / Sex:** {ctx.age_years} / {ctx.sex}",
        f"**Exam date:** {procedure.effective_date.isoformat()}",
        "",
        "## Examination",
        f"- **Procedure:** {procedure.code.display}",
        f"- **Code:** {procedure.code.system} {procedure.code.code}",
        "",
        "## Clinical indication",
        f"Evaluation of {indication}.",
        "",
        "## Technique",
        f"Standard protocol for {procedure.code.display} per synthetic module emit.",
        "",
        "## Comparison",
        "No prior imaging available for comparison in this synthetic record.",
        "",
        "## Findings",
        "Findings are synthesized to remain consistent with the patient's structured "
        "problem list and module context. No acute life-threatening abnormality "
        "documented beyond what the active conditions imply.",
        "",
        "## Impression",
        f"1. {procedure.code.display} performed for evaluation of {indication}.",
        "2. Correlate clinically; recommend follow-up imaging only if symptoms persist "
        "or treating clinician requests interval study.",
        "",
        "---",
        "_Generated by APEX Atlas (template mode). "
        "This is synthetic data; no real patient is depicted._",
    ]
    return "\n".join(lines)
