#!/usr/bin/env python3
"""Build the public fidelity scorecard.

For every module that ships a bundled fidelity expectation, generate a focused
single-module cohort (so cross-module progressions can't inflate a progression
target's prevalence), run the cohort harness, and emit a consolidated Markdown
scorecard at docs/fidelity-scorecard.md.

The scorecard is the clickable artifact behind Atlas's "validated against public
norms" claim: per module, how many metric strata fall within tolerance of the
cited target, and the worst observed deviation.

Usage:
    python scripts/build_fidelity_scorecard.py [--patients N] [--seed S] [--out PATH]

Deterministic given (--patients, --seed). Run from the repo root with the
package importable (e.g. `PYTHONPATH=src`).
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
import tempfile
from datetime import date
from pathlib import Path

from parker_atlas.validation.cohort import evaluate_cohort
from parker_atlas.validation.expectations import (
    list_bundled_expectations,
    load_bundled_expectation,
)

REPO = Path(__file__).resolve().parents[1]
CATALOG = REPO / "docs" / "module-catalog.md"


def _domain_map() -> dict[str, str]:
    """module -> domain, parsed from the catalog's Current Library table."""
    out: dict[str, str] = {}
    if not CATALOG.is_file():
        return out
    in_table = False
    for line in CATALOG.read_text(encoding="utf-8").splitlines():
        if line.strip() == "## Current Library":
            in_table = True
            continue
        if in_table and line.startswith("## "):
            break
        if not in_table or not line.startswith("| "):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) >= 2 and cells[0] not in {"Module", "---"}:
            out[cells[0]] = cells[1]
    return out


def _generate(module: str, out_dir: Path, patients: int, seed: int) -> bool:
    cmd = [
        sys.executable, "-m", "parker_atlas.cli", "generate",
        "--module", module, "--patients", str(patients), "--seed", str(seed),
        "--out", str(out_dir),
    ]
    res = subprocess.run(cmd, capture_output=True, text=True)
    if res.returncode != 0:
        sys.stderr.write(f"  generate failed for {module}: {res.stderr[-300:]}\n")
        return False
    return len(list(out_dir.glob("GPX-SYN-*.json"))) > 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--patients", type=int, default=8000)
    ap.add_argument("--seed", type=int, default=20260604)
    ap.add_argument("--out", type=Path, default=REPO / "docs" / "fidelity-scorecard.md")
    args = ap.parse_args()

    modules = list_bundled_expectations()
    domains = _domain_map()
    rows = []
    tot_metrics = tot_pass = 0

    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        for i, module in enumerate(modules, 1):
            sys.stderr.write(f"[{i}/{len(modules)}] {module}\n")
            cohort = tmp_path / module
            if not _generate(module, cohort, args.patients, args.seed):
                rows.append((module, domains.get(module, "—"), "?", 0, 0, None, "GEN-FAIL"))
                continue
            exp = load_bundled_expectation(module)
            report = evaluate_cohort(cohort, exp, min_samples=30)
            results = report.results
            n_metrics = len(results)
            n_pass = sum(1 for r in results if r.within_tolerance)
            worst = max((abs(r.actual - r.target) for r in results), default=None)
            tot_metrics += n_metrics
            tot_pass += n_pass
            status = "PASS" if n_metrics and n_pass == n_metrics else (
                "FAIL" if n_metrics else "NO-DATA"
            )
            rows.append(
                (module, domains.get(module, "—"), exp.source.provenance,
                 n_metrics, n_pass, worst, status)
            )

    md = _render(rows, tot_metrics, tot_pass, args)
    args.out.write_text(md, encoding="utf-8")
    sys.stderr.write(f"\nWrote {args.out} ({tot_pass}/{tot_metrics} strata within tolerance)\n")
    return 0


def _render(rows, tot_metrics, tot_pass, args) -> str:
    n_modules = len(rows)
    n_pass_modules = sum(1 for r in rows if r[6] == "PASS")
    pct = (100.0 * tot_pass / tot_metrics) if tot_metrics else 0.0
    lines = [
        "# Apex Atlas — Fidelity Scorecard",
        "",
        "_Auto-generated by `scripts/build_fidelity_scorecard.py`. Do not edit by hand._",
        "",
        f"Every module that ships a sourced fidelity expectation is generated as a "
        f"focused single-module cohort (N={args.patients:,} per module, seed "
        f"{args.seed}) and checked against its cited target rates by the cohort "
        f"harness. Single-module cohorts isolate each module so cross-module "
        f"progressions cannot inflate a progression target's prevalence.",
        "",
        "## Summary",
        "",
        f"- **Modules scored:** {n_modules}",
        f"- **Modules fully within tolerance:** {n_pass_modules} / {n_modules}",
        f"- **Metric strata within tolerance:** {tot_pass} / {tot_metrics} ({pct:.1f}%)",
        "",
        "Tolerance is per-expectation (Wilson score interval at the stated "
        "confidence). A module passes when every age/sex stratum it declares "
        "falls within tolerance of its cited target.",
        "",
        "> **Reading marginal breaches.** This is a single-seed snapshot. With "
        "hundreds of strata checked at ~99% per-stratum confidence, a handful of "
        "single-stratum breaches with small |Δ| are expected from multiple "
        "comparisons, not miscalibration — re-running at another seed typically "
        "clears them. Persistent, multi-stratum, or large-|Δ| breaches are the "
        "ones that indicate a real calibration gap.",
        "",
        "## Per-module results",
        "",
        "| Module | Domain | Provenance | Strata | Within tol. | Worst |Δ| | Status |",
        "|---|---|---|---:|---:|---:|---|",
    ]
    for module, domain, prov, n_metrics, n_pass, worst, status in sorted(rows):
        worst_s = f"{worst:.3f}" if worst is not None else "—"
        badge = {"PASS": "✅ pass", "FAIL": "❌ fail",
                 "GEN-FAIL": "⚠️ gen-fail", "NO-DATA": "— no-data"}.get(status, status)
        lines.append(
            f"| {module} | {domain} | {prov} | {n_metrics} | {n_pass} | {worst_s} | {badge} |"
        )
    lines += [
        "",
        "## Not yet scored",
        "",
        "- **sickle_cell** — modeled prevalence is ~0 at cohort level; needs a "
        "targeted cohort or higher modeled rate.",
        "- **osteoarthritis, pulmonary_hypertension** — declared rates do not "
        "reproduce reliably within tolerance; calibration tracked in issue #8.",
        "",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    raise SystemExit(main())
